# Generated by Django 4.0.4 on 2022-06-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/noimage.webp', upload_to='media/'),
        ),
    ]
